# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeTeleport < Formula
  desc "Move your Claude Code history between machines, with paths fixed automatically"
  homepage "https://github.com/gowtham-sai-yadav/claude-teleport"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v0.5.0/claude-teleport-darwin-amd64"
      sha256 "11fd5ca0412476c672927dabab64991c884baf1dd8c89819de7d2c053a208faf"

      define_method(:install) do
        bin.install "claude-teleport-darwin-amd64" => "claude-teleport"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v0.5.0/claude-teleport-darwin-arm64"
      sha256 "8f15e0c01b71f03603c7c817c74100b8c39638f2b70e81016cb894399e9ff250"

      define_method(:install) do
        bin.install "claude-teleport-darwin-arm64" => "claude-teleport"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v0.5.0/claude-teleport-linux-amd64"
      sha256 "2744021d3b1871e12a76f7786aebae2d7c3dd69cd6a04b90fc1574b0e0282055"
      define_method(:install) do
        bin.install "claude-teleport-linux-amd64" => "claude-teleport"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v0.5.0/claude-teleport-linux-arm64"
      sha256 "545bb484e122c7120daf26f4bc59539eebcc1ec726bbca9fe94e2901cc65c759"
      define_method(:install) do
        bin.install "claude-teleport-linux-arm64" => "claude-teleport"
      end
    end
  end

  test do
    system "#{bin}/claude-teleport", "version"
  end
end
