# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeTeleport < Formula
  desc "Move your Claude Code history between machines, with paths fixed automatically"
  homepage "https://github.com/gowtham-sai-yadav/claude-teleport"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v0.5.2/claude-teleport-darwin-amd64"
      sha256 "afc2b620cc0ff9d5d73dd15129818bc67ccab274339d14cc25d7d93326360afe"

      define_method(:install) do
        bin.install "claude-teleport-darwin-amd64" => "claude-teleport"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v0.5.2/claude-teleport-darwin-arm64"
      sha256 "536db5c5a8a8ac7ce0214120146dcaee2e11ffa69929714e942022d09b2ef58c"

      define_method(:install) do
        bin.install "claude-teleport-darwin-arm64" => "claude-teleport"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v0.5.2/claude-teleport-linux-amd64"
      sha256 "8de0070b96a7da0948679dcfcecb02795ce1e423283cf7c633fc47c4d73420a5"
      define_method(:install) do
        bin.install "claude-teleport-linux-amd64" => "claude-teleport"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v0.5.2/claude-teleport-linux-arm64"
      sha256 "c4d5517b0020b1223f708fa8fd558fb709cae13f3e6b5cbae89b60adb9ad619b"
      define_method(:install) do
        bin.install "claude-teleport-linux-arm64" => "claude-teleport"
      end
    end
  end

  test do
    system "#{bin}/claude-teleport", "version"
  end
end
