# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeTeleport < Formula
  desc "Move your Claude Code history between machines, with paths fixed automatically"
  homepage "https://github.com/gowtham-sai-yadav/claude-teleport"
  version "0.5.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v0.5.5/claude-teleport-darwin-amd64"
      sha256 "27f0f045171a8de40bf049b70da3b2e0ee7b7dad5d9f244528dcddc20adba63b"

      define_method(:install) do
        bin.install "claude-teleport-darwin-amd64" => "claude-teleport"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v0.5.5/claude-teleport-darwin-arm64"
      sha256 "0033bfc8557b2d571de6cc04a7896e3961de8245c70fb4844b00cde762ef463f"

      define_method(:install) do
        bin.install "claude-teleport-darwin-arm64" => "claude-teleport"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v0.5.5/claude-teleport-linux-amd64"
      sha256 "65f961e0715d7d9274b6b68dbe0921348200a765df76042d41bbfa20ec456b01"
      define_method(:install) do
        bin.install "claude-teleport-linux-amd64" => "claude-teleport"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v0.5.5/claude-teleport-linux-arm64"
      sha256 "0b4695839caae3d3846b5ed06558fd354516280700a6a015fadca8b98b409b85"
      define_method(:install) do
        bin.install "claude-teleport-linux-arm64" => "claude-teleport"
      end
    end
  end

  test do
    system "#{bin}/claude-teleport", "version"
  end
end
