# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Entangle < Formula
  desc "Hand a live coding session to anyone - Claude Code, Codex, or opencode"
  homepage "https://github.com/gowtham-sai-yadav/entangle"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gowtham-sai-yadav/entangle/releases/download/v0.7.0/entangle-darwin-amd64"
      sha256 "6e2cedef3d023917cb311faf148f775311804d80f940ead44944dde5b574cf59"

      define_method(:install) do
        bin.install "entangle-darwin-amd64" => "entangle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gowtham-sai-yadav/entangle/releases/download/v0.7.0/entangle-darwin-arm64"
      sha256 "29d652d68fb9881d6379c04b6522ef87d33812a463c8fa063614fb4d9f9b64a3"

      define_method(:install) do
        bin.install "entangle-darwin-arm64" => "entangle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gowtham-sai-yadav/entangle/releases/download/v0.7.0/entangle-linux-amd64"
      sha256 "2104196d64ca334116196f4a6a3008676aa69cb34ea7724bbf9b41f41ba8afbb"
      define_method(:install) do
        bin.install "entangle-linux-amd64" => "entangle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gowtham-sai-yadav/entangle/releases/download/v0.7.0/entangle-linux-arm64"
      sha256 "534dcd9e7106a848c69fd6f6a3a0ef8a29e10328229fb49565786fada899d2bf"
      define_method(:install) do
        bin.install "entangle-linux-arm64" => "entangle"
      end
    end
  end

  test do
    system "#{bin}/entangle", "version"
  end
end
