# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Entangle < Formula
  desc "Hand a live coding session to anyone - Claude Code, Codex, or opencode"
  homepage "https://github.com/gowtham-sai-yadav/entangle"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gowtham-sai-yadav/entangle/releases/download/v0.6.0/entangle-darwin-amd64"
      sha256 "47c28a55aaf8b91d7254116dc6e0b6cf1fb1674ca853e71cda058b7960b1eb47"

      define_method(:install) do
        bin.install "entangle-darwin-amd64" => "entangle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gowtham-sai-yadav/entangle/releases/download/v0.6.0/entangle-darwin-arm64"
      sha256 "48d949de7e528f03d570a2c86ce735eba6fc61f619726cb51f4ea17bb8d2a0ca"

      define_method(:install) do
        bin.install "entangle-darwin-arm64" => "entangle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gowtham-sai-yadav/entangle/releases/download/v0.6.0/entangle-linux-amd64"
      sha256 "881033979f22ef0e8ecee19e154c37205902bb87f885859383d53928549a3530"
      define_method(:install) do
        bin.install "entangle-linux-amd64" => "entangle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gowtham-sai-yadav/entangle/releases/download/v0.6.0/entangle-linux-arm64"
      sha256 "e94e3711e714f8e5a69b4d3efcfcf4e41b403b7eadbb0d5d4b8bd228857502ab"
      define_method(:install) do
        bin.install "entangle-linux-arm64" => "entangle"
      end
    end
  end

  test do
    system "#{bin}/entangle", "version"
  end
end
