# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-teleport" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "093d6bd18f1acaf6d486ea4222d36f7c6befea1582069d9ce784269ac57e8d4c"
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v#{version}/claude-teleport-darwin-amd64"
      binary "claude-teleport-darwin-amd64", target: "claude-teleport"
    end
    on_arm do
      sha256 "0d7ded1bd252194e96f61f34f5ce79b6e0570d2f01cc4a0256f131bd0a1cd6e7"
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v#{version}/claude-teleport-darwin-arm64"
      binary "claude-teleport-darwin-arm64", target: "claude-teleport"
    end
  end

  on_linux do
    on_intel do
      sha256 "73fa17b907a88f3ab11f877542b9080dd4628694a6d6b1fe1765568af1e5577d"
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v#{version}/claude-teleport-linux-amd64"
      binary "claude-teleport-linux-amd64", target: "claude-teleport"
    end
    on_arm do
      sha256 "995c5120cf867003a4276e956c516bfb5784b325e1af052081382f4098f355e7"
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v#{version}/claude-teleport-linux-arm64"
      binary "claude-teleport-linux-arm64", target: "claude-teleport"
    end
  end

  name "claude-teleport"
  desc "Move your Claude Code history between machines, with paths fixed automatically"
  homepage "https://github.com/gowtham-sai-yadav/claude-teleport"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
