# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-teleport" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "4a8273206062bd9feb18a3d3f2d13dc12e15845083c76d75d25cf9526e6456aa"
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v#{version}/claude-teleport-darwin-amd64"
      binary "claude-teleport-darwin-amd64", target: "claude-teleport"
    end
    on_arm do
      sha256 "9cbb10853a131367dacfc4cac6d3aa3c4a94b70b4057d1254ac27b22300cbd64"
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v#{version}/claude-teleport-darwin-arm64"
      binary "claude-teleport-darwin-arm64", target: "claude-teleport"
    end
  end

  on_linux do
    on_intel do
      sha256 "58ed6022ce9ee0ba3909ce4959684a1bcbffcea506e4ca97ea59b707fa9d5f6e"
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v#{version}/claude-teleport-linux-amd64"
      binary "claude-teleport-linux-amd64", target: "claude-teleport"
    end
    on_arm do
      sha256 "345217ca495f7685f2c73b00a0854680fc08e93e4fdf976d2952c7fc62296618"
      url "https://github.com/gowtham-sai-yadav/claude-teleport/releases/download/v#{version}/claude-teleport-linux-arm64"
      binary "claude-teleport-linux-arm64", target: "claude-teleport"
    end
  end

  name "claude-teleport"
  desc "Move your Claude Code history between machines, with paths fixed automatically"
  homepage "https://github.com/gowtham-sai-yadav/claude-teleport"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
